# Docker Compose configuration file
#
# References:
#
# * Compose Specification | Compose file reference | Reference | Docker Docs
#   https://docs.docker.com/compose/compose-file/
#
# Copyright 2025 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0
name: project-name
services:
  # Environment for testing the project
  test-environment:
    container_name: project-name-test
    hostname: project-name-test
    image: ubuntu:24.04
    volumes:
      - type: bind
        source: ./
        target: /project
    environment:
      # Pass host proxy settings to the container
      - http_proxy
      - HTTP_PROXY
      - https_proxy
      - HTTPS_PROXY
      - no_proxy
      - NO_PROXY

      # Set this environment variable to your local timezone settings
      # for proper operation timestamp
      #- TZ=CST-8
    command: sleep infinity
